from sqlalchemy import Column, Integer, String, Float, JSON
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Stops(Base):
    __tablename__ = 'stops'
    tractor_id = Column(Integer, primary_key=True, index=True)
    trip_id = Column(Integer, primary_key=True, index=True)
    stop_type = Column(String)
    latitude = Column(Float)
    longitude = Column(Float)
    arrival_datetime = Column(String)
    departure_datetime = Column(String)
    miles_travelled = Column(Float)
    dwell_time = Column(Float)
    fuel_latitude = Column(Float)
    fuel_longitude = Column(Float)
    fuel_tank_percent_before = Column(Float)
    fuel_tank_percent_after = Column(Float)
    fuel_location_name = Column(String)
    unit_price = Column(Float)
    total_cost = Column(Float)
    quantity = Column(Float)
    city = Column(String)
    state = Column(String)
    is_warehouse = Column(String)
    nearest1_name = Column(String)
    nearest1_amenity = Column(String)
    nearest1_building = Column(String)
    nearest1_shop = Column(String)
    nearest1_highway = Column(String)
    nearest1_coords = Column(JSON)
    nearest2_name = Column(String)
    nearest2_amenity = Column(String)
    nearest2_building = Column(String)
    nearest2_shop = Column(String)
    nearest2_highway = Column(String)
    nearest2_coords = Column(JSON)
    nearest3_name = Column(String)
    nearest3_amenity = Column(String)
    nearest3_building = Column(String)
    nearest3_shop = Column(String)
    nearest3_highway = Column(String)
    nearest3_coords = Column(JSON)
    nearest4_name = Column(String)
    nearest4_amenity = Column(String)
    nearest4_building = Column(String)
    nearest4_shop = Column(String)
    nearest4_highway = Column(String)
    nearest4_coords = Column(JSON)
    nearest5_name = Column(String)
    nearest5_amenity = Column(String)
    nearest5_building = Column(String)
    nearest5_shop = Column(String)
    nearest5_highway = Column(String)
    nearest5_coords = Column(JSON)
    type_new = Column(String)
    near_mechanic = Column(Integer)

class Places(Base):
    __tablename__ = 'places'
    name = Column(String, primary_key=True, index=True)
    latitude = Column(Float)
    longitude = Column(Float)
    amenity = Column(String)
    building = Column(String)
    shop = Column(String)
    highway = Column(String)

class Trips(Base):
    __tablename__ = 'trips'
    tractor_id = Column(Integer, primary_key=True, index=True)
    trip_id = Column(Integer, primary_key=True, index=True)
    country = Column(String)
    state = Column(String)
    city = Column(String)
    address = Column(String)
    postal_code = Column(String)
    latitude = Column(Float)
    longitude = Column(Float)
    odometer = Column(Float)
    load_status = Column(String)
    to_state = Column(String)
    to_city = Column(String)
    to_country = Column(String)
    to_address = Column(String)
    to_postal_code = Column(String)
    to_latitude = Column(Float)
    to_longitude = Column(Float)
    arrival_datetime = Column(String)
    to_arrival_datetime = Column(String)
    trip_ref_norm = Column(String)
    gps = Column(String)
    fuel = Column(String)
    unit_tank = Column(String)